#!/usr/bin/env bash
set -e

echo "[*] Installing programs..."

sudo pacman -S --needed --noconfirm \
    i3-wm \
    xorg-server \
    xorg-xinit \
    xorg-xrandr \
    rxvt-unicode \
    ranger \
    w3m \
    feh \
    rofi \
    nerd-fonts \
    noto-fonts \
    ttf-fira-code \
    pulseaudio \
    pulsemixer \
    firefox \
    discord \
    gnome-keyring \
    libsecret \
    scrot \
    redshift \
    keepassxc \
    vim \
    zip \
    unzip \
    gcc \
    make \
    cmake \
    which \
    openssh \
    rsync \

yay -S --needed --noconfirm \
    polybar \
    visual-studio-code-bin \
    slack-desktop \

echo "Done."