#!/usr/bin/env bash
set -e

echo "[*] Installing LaTeX packages..."

sudo pacman -S --needed --noconfirm \
    texlive-core \
    texlive-latexextra \
    texlive-bibtexextra \
    texlive-binextra \
    texlive-plaingeneric \
    texlive-fontsrecommended \
    texlive-fontsextra \

echo "Done."