#!/usr/bin/env bash
set -e

echo "[*] Configuring git..."
git config --global user.email "$EMAIL"
git config --global user.name "$NAME"

echo "[*] Generating SSH key..."
ssh-keygen -t ed25519 -C "$EMAIL"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

echo "[*] Setting up GitHub SSH URLS..."
git config --global url."git@github.com:".insteadOf "https://github.com/"

echo "[*] Updating dotfiles remote URL..."
dotfiles remote set-url origin git@github.com:$GITHUB_USERNAME/dotfiles.git

echo "Done."