#!/usr/bin/env bash

set -euo pipefail

template_file="$HOME/.config/fastfetch/config_template.jsonc"
output_file="$HOME/.config/fastfetch/config.jsonc"

source ~/.config/colors

envsubst < "$template_file" > "$output_file"