#!/bin/bash

source ~/.bashrc

case "${1##*.}" in
    py)
        .venv/bin/python "$1"
        ;;
    tex)
        cd "$(dirname "$1")"
        latexmk -pdf -interaction=nonstopmode -f "$(basename "$1")"
        latexmk -c "$(basename "$1")"
        ;;
    *)
        echo "No build command defined for .$extension files"
        exit 1
        ;;
esac