#!/usr/bin/env bash

REMOTE_ADDRESS="desktop"
REMOTE_PORT=8888
LOCAL_PORT=8888
LOCAL_URL="http://localhost:${LOCAL_PORT}/lab/tree/dev"

cleanup() {
    echo -e "\nCaught Ctrl+C. Closing tunnel and killing remote Jupyter process..."

    ssh ${REMOTE_ADDRESS} "taskkill /F /IM python.exe /T >NUL 2>&1" &

    sleep 1
    kill $BROWSER_PID >/dev/null 2>&1
    
    exit 0
}
trap cleanup INT TERM

echo "Starting Jupyter Notebook on $REMOTE_ADDRESS..."

ssh -t -L ${LOCAL_PORT}:localhost:${REMOTE_PORT} ${REMOTE_ADDRESS} \
  "jupyter lab --no-browser --port=${REMOTE_PORT} --NotebookApp.token='' --NotebookApp.password=''" 2>/dev/null &
SSH_PID=$!

sleep 5

echo "Tunnel established. Opening ${LOCAL_URL}..."
xdg-open "${LOCAL_URL}" >/dev/null 2>&1 &
BROWSER_PID=$!

echo "Press Ctrl+C to close."

wait $SSH_PID
