#!/usr/bin/env bash

VS_CODE="/usr/bin/code"
JUPYTER="/usr/bin/jupyter lab"
FEH="/usr/bin/feh --auto-zoom --scale-down --start-at"
FIREFOX="/usr/bin/firefox"

declare -A programs=(
  [png]="$FEH"
  [jpg]="$FEH"
  [jpeg]="$FEH"
  [pdf]="$FIREFOX"
  [txt]="$VS_CODE"
  [dat]="$VS_CODE"
  [py]="$VS_CODE"
  [c]="$VS_CODE"
  [cpp]="$VS_CODE"
  [h]="$VS_CODE"
  [ipynb]="$JUPYTER"
)

default_program="$VS_CODE"

if [[ $# -eq 0 ]]; then
  echo "No files provided."
  exit 1
fi

for file in "$@"; do
  if [[ ! -e "$file" ]]; then
    echo "File not found: $file"
    continue
  fi

  ext="${file##*.}"
  ext="${ext,,}"  # lowercase
  program="${programs[$ext]:-$default_program}"

  # echo "Opening $file with $program"
  nohup $program "$file" >/dev/null 2>&1 &
done
