#!/usr/bin/env python

import sys
from subprocess import Popen

set_programs = {
    # Images
    'png': '/usr/bin/qimgv',
    'jpg': '/usr/bin/qimgv',
    # PDFs
    'pdf': '/usr/bin/firefox',
    # Text and Code
    'txt': '/usr/bin/code',
    'dat': '/usr/bin/code',
    'py': '/usr/bin/code',
    'c': '/usr/bin/code',
    'cpp': '/usr/bin/code',
    'h': '/usr/bin/code',
}

default_program = '/usr/bin/code'

def open_fn(file: str):
    file_ext = file.split('.')[-1]
    try:
        program = set_programs[file_ext]
    except KeyError:
        program = default_program

    print(f'Opening {file} with {program}')
    Popen([program, file], stdin=None, stdout=None, stderr=None)

args = sys.argv[1:]

if not args:
    sys.exit('No given files to open')

for arg in args:
    open_fn(arg)
