#!/usr/bin/python
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')
from spextractor import Spextractor
import sys


file, z = sys.argv[1:]
z = float(z)


spex = Spextractor(file, z=z)
