#!/usr/bin/bash
plot_func='$HOME/.bin/plot_simple'
redshift='0.0'

while getopts 'sz:' flag; do
    case "${flag}" in
        s) plot_func='$HOME/.bin/plot_spex' ;;
        z) redshift="${OPTARG}" ;;
    esac
done

shift $((OPTIND - 1))

if [ -z "${1}" ]
then
    echo "Usage: plot [-s] filename" ;
    exit 1
fi

files="${1}"

cmd="python ${plot_func} ${files} ${redshift}"
eval $cmd