#!/usr/bin/env bash

set -euo pipefail

clear

resources_file=$HOME/.Xresources
colors_file=$HOME/.config/colors

if [ -f $colors_file ]; then
    set -a
    source $colors_file
    set +a
fi

$HOME/.config/fastfetch/gen_config
$HOME/.config/alacritty/gen_config

$HOME/.config/Xresources/gen_Xresources
if [ -f "$resources_file" ]; then
    xrdb -merge "$resources_file"
fi

$HOME/.config/polybar/launch.sh > /dev/null 2>&1 &